import os
import json
import uuid
import markdown
from xhtml2pdf import pisa
from io import BytesIO
from app.models import IntelligenceBrief, User, Case, Criminal
from app.extensions import db
from app.services.agents import SupervisorAgent

class PDFService:
    @staticmethod
    def generate_pdf(markdown_text):
        html_content = f"""
        <html>
        <head>
        <style>
            body {{ font-family: Helvetica, sans-serif; font-size: 12pt; line-height: 1.5; color: #333; }}
            h1 {{ color: #1e3a8a; border-bottom: 2px solid #1e3a8a; padding-bottom: 5px; }}
            h2 {{ color: #2563eb; margin-top: 20px; }}
            h3 {{ color: #3b82f6; }}
            p {{ margin-bottom: 10px; }}
            ul {{ margin-bottom: 10px; }}
            li {{ margin-bottom: 5px; }}
            .highlight {{ background-color: #fef08a; padding: 2px; }}
            .footer {{ font-size: 8pt; color: #666; text-align: center; margin-top: 30px; border-top: 1px solid #ccc; padding-top: 5px; }}
        </style>
        </head>
        <body>
            {markdown.markdown(markdown_text)}
            <div class="footer">Generated by SentinelAI Executive Command Center - CONFIDENTIAL</div>
        </body>
        </html>
        """
        result = BytesIO()
        pdf = pisa.pisaDocument(BytesIO(html_content.encode("utf-8")), result)
        if not pdf.err:
            return result.getvalue()
        return None

class BriefGenerator:
    def generate_brief(self, entity_type, entity_id):
        # 1. Gather Intelligence using SupervisorAgent
        supervisor = SupervisorAgent()
        result = supervisor.execute(entity_type, entity_id)
        
        if "error" in result:
             return {"error": result["error"]}
             
        # Resolve Title
        title = f"Intelligence Brief: {entity_id}"
        if entity_type == 'criminal':
             c = Criminal.query.get(entity_id)
             if c: title = f"Target Profile: {c.name}"
        elif entity_type == 'case':
             c = Case.query.get(entity_id)
             if c: title = f"Case Summary: {c.title}"
             
        # Mocking Severity for Hackathon
        severity = "High" if result.get("confidence", 0) > 0.9 else "Medium"
        if 'cyber' in title.lower() or 'heist' in title.lower():
             severity = "Critical"
             
        # Standardized Template
        markdown_report = result.get("report", "")
        if not markdown_report.startswith("#"):
             markdown_report = f"# {title}\n\n" + markdown_report
             
        # Append Lead Section if not heavily present
        leads = result.get("leads", [])
        if leads:
             markdown_report += "\n\n## Recommended Investigative Leads\n"
             for i, lead in enumerate(leads):
                  markdown_report += f"{i+1}. {lead}\n"

        # 2. Persist to Database
        system_user = User.query.first()
        user_id = system_user.id if system_user else 'system'
        
        confidence_val = result.get("confidence", 1.0)
        final_status = 'failed' if confidence_val <= 0 else 'completed'

        brief = IntelligenceBrief(
             id=str(uuid.uuid4()),
             case_id=entity_id,
             generated_by=user_id,
             title=title,
             content_markdown=markdown_report,
             audit_trail_json=json.dumps(result.get("raw_data", {})),
             severity=severity,
             confidence_score=confidence_val,
             status=final_status
        )
        db.session.add(brief)
        db.session.commit()
        
        return brief.to_dict()
