import { useEffect, useState } from 'react';
import { fetchCases, fetchCriminals, fetchBriefs } from '../services/api';
import { Briefcase, ShieldAlert, Target, FileText, Activity, AlertTriangle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const Dashboard = () => {
  const [stats, setStats] = useState({ cases: 0, criminals: 0, briefs: 0 });
  const [recentBriefs, setRecentBriefs] = useState([]);
  const navigate = useNavigate();

  useEffect(() => {
    Promise.all([fetchCases(), fetchCriminals(), fetchBriefs()]).then(([cases, criminals, briefs]) => {
      setStats({ cases: cases.length, criminals: criminals.length, briefs: briefs.length });
      setRecentBriefs(briefs.slice(0, 5));
    });
  }, []);

  const kpis = [
    { title: "Active Cases", value: stats.cases, icon: Briefcase, color: "text-blue-500", bg: "bg-blue-500/10 border-blue-500/20" },
    { title: "Target Profiles", value: stats.criminals, icon: Target, color: "text-red-500", bg: "bg-red-500/10 border-red-500/20" },
    { title: "Generated Briefs", value: stats.briefs, icon: FileText, color: "text-green-500", bg: "bg-green-500/10 border-green-500/20" }
  ];

  return (
    <div className="h-full flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-semibold">Executive Command Center</h1>
        <p className="text-muted mt-1">High-level overview of intelligence operations and system activity.</p>
      </div>
      
      {/* KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {kpis.map((kpi, i) => {
          const Icon = kpi.icon;
          return (
            <div key={i} className={`glass-panel p-6 border ${kpi.bg}`}>
              <div className="flex justify-between items-start">
                <div>
                  <p className="text-sm font-medium text-muted uppercase tracking-wider mb-2">{kpi.title}</p>
                  <h3 className="text-4xl font-bold">{kpi.value}</h3>
                </div>
                <div className={`p-3 rounded-lg ${kpi.bg} ${kpi.color}`}>
                  <Icon size={24} />
                </div>
              </div>
            </div>
          )
        })}
      </div>

      <div className="grid grid-cols-3 gap-6 flex-1 overflow-hidden">
        
        {/* Recent Intelligence Activity */}
        <div className="col-span-2 glass-panel p-6 flex flex-col">
          <h2 className="text-lg font-semibold flex items-center gap-2 mb-6"><Activity className="text-blue-500"/> Recent Intelligence Activity</h2>
          <div className="flex-1 overflow-y-auto space-y-4 pr-2">
            {recentBriefs.map(brief => (
              <div key={brief.id} onClick={() => navigate('/briefs')} className="p-4 bg-surface border border-border rounded-lg flex justify-between items-center cursor-pointer hover:border-blue-500/50 transition-colors">
                <div className="flex items-center gap-4">
                  <div className={`w-10 h-10 rounded-full flex items-center justify-center ${brief.severity === 'Critical' ? 'bg-red-500/10 text-red-500' : 'bg-blue-500/10 text-blue-500'}`}>
                    <FileText size={18} />
                  </div>
                  <div>
                    <h4 className="font-medium text-sm">{brief.title}</h4>
                    <p className="text-xs text-muted mt-1">Generated by Agent Pipeline • {new Date(brief.created_at).toLocaleString()}</p>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <span className={`text-xs font-bold uppercase tracking-wider px-2 py-1 rounded ${brief.severity === 'Critical' ? 'bg-red-500/10 text-red-500' : 'bg-orange-500/10 text-orange-400'}`}>
                    {brief.severity} Severity
                  </span>
                </div>
              </div>
            ))}
            {recentBriefs.length === 0 && <p className="text-sm text-muted">No recent intelligence activity.</p>}
          </div>
        </div>

        {/* System Health / Status */}
        <div className="col-span-1 glass-panel p-6">
          <h2 className="text-lg font-semibold flex items-center gap-2 mb-6"><ShieldAlert className="text-blue-500"/> System Health</h2>
          <div className="space-y-4">
            <div className="p-4 bg-green-500/5 border border-green-500/20 rounded-lg">
              <div className="flex justify-between items-center mb-2">
                <span className="text-sm font-medium text-green-400">Database Connection</span>
                <span className="w-2 h-2 rounded-full bg-green-500"></span>
              </div>
              <p className="text-xs text-muted">Operational</p>
            </div>
            <div className="p-4 bg-green-500/5 border border-green-500/20 rounded-lg">
              <div className="flex justify-between items-center mb-2">
                <span className="text-sm font-medium text-green-400">Gemini AI Pipeline</span>
                <span className="w-2 h-2 rounded-full bg-green-500"></span>
              </div>
              <p className="text-xs text-muted">Operational</p>
            </div>
            <div className="p-4 bg-green-500/5 border border-green-500/20 rounded-lg">
              <div className="flex justify-between items-center mb-2">
                <span className="text-sm font-medium text-green-400">Network Topology Engine</span>
                <span className="w-2 h-2 rounded-full bg-green-500"></span>
              </div>
              <p className="text-xs text-muted">Operational</p>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};

export default Dashboard;
