import { useEffect, useState } from 'react';
import { fetchForecastDashboard } from '../services/api';
import { TrendingUp, Activity, MapPin, AlertTriangle, ChevronRight, BarChart2 } from 'lucide-react';

const Forecast = () => {
  const [data, setData] = useState({ trends: [], hotspots: [], alerts: [], escalations: [] });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchForecastDashboard()
      .then(res => {
        setData(res);
        setLoading(false);
      })
      .catch(console.error);
  }, []);

  const getCategoryClass = (category) => {
    if (category === 'Critical') return 'bg-red-500/10 text-red-500 border-red-500/20';
    if (category === 'Elevated') return 'bg-orange-500/10 text-orange-500 border-orange-500/20';
    if (category === 'Watchlist') return 'bg-yellow-500/10 text-yellow-500 border-yellow-500/20';
    return 'bg-green-500/10 text-green-500 border-green-500/20';
  };

  if (loading) return <div className="p-8 text-center text-muted">Analyzing temporal momentum matrices...</div>;

  return (
    <div className="h-[calc(100vh-8rem)] flex gap-6 overflow-hidden">
      
      {/* Left Panel: Early Warning Feed */}
      <div className="w-80 glass-panel flex flex-col overflow-hidden">
        <div className="p-5 border-b border-border bg-surface/50">
          <h2 className="font-semibold flex items-center gap-2 text-red-400"><AlertTriangle size={18}/> Early Warning Feed</h2>
          <p className="text-xs text-muted mt-1">Generated by AlertGenerator.</p>
        </div>
        <div className="flex-1 overflow-y-auto p-4 space-y-3">
          {data.alerts.map((a, i) => (
             <div key={i} className="bg-background border border-red-500/20 rounded-lg p-3 border-l-2 border-l-red-500">
               <div className="text-[10px] uppercase font-bold text-red-500 tracking-wider mb-1">{a.type} ALERT</div>
               <p className="text-xs text-gray-300 leading-relaxed">{a.message}</p>
             </div>
          ))}
          {data.alerts.length === 0 && <p className="text-xs text-muted">No early warnings detected.</p>}
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 flex flex-col gap-6 overflow-hidden">
        
        {/* Top: Crime Trends */}
        <div className="h-1/2 glass-panel flex flex-col overflow-hidden">
           <div className="p-5 border-b border-border bg-surface/50">
             <h2 className="font-semibold flex items-center gap-2"><TrendingUp size={18} className="text-blue-500"/> Emerging Crime Trends</h2>
           </div>
           <div className="flex-1 overflow-y-auto p-5 grid grid-cols-2 gap-4">
             {data.trends.map((t, i) => (
                <div key={i} className="bg-surface border border-border p-5 rounded-lg flex flex-col gap-3 relative overflow-hidden">
                  <div className="flex justify-between items-start z-10">
                    <div>
                      <h3 className="font-bold text-lg text-white">{t.entity_id}</h3>
                      <p className="text-[10px] uppercase font-semibold text-blue-400 tracking-wider">Vol: {t.current_volume} Cases</p>
                    </div>
                    <span className={`px-2 py-1 rounded text-[10px] font-bold uppercase tracking-widest border ${getCategoryClass(t.category)}`}>
                      {t.category}
                    </span>
                  </div>
                  
                  <div className="bg-background/50 border border-border p-3 rounded-lg z-10 mt-auto">
                    <p className="text-sm font-semibold text-white mb-1">{t.prediction}</p>
                    <p className="text-xs text-muted flex items-start gap-1"><ChevronRight size={14} className="shrink-0 mt-0.5 text-blue-500"/> {t.reason}</p>
                    <div className="mt-3 flex justify-between items-center text-[10px] uppercase text-muted font-bold tracking-wider">
                       <span>Engine Confidence</span>
                       <span className="text-green-400">{(t.confidence * 100).toFixed(0)}%</span>
                    </div>
                  </div>
                  {/* Background Bar */}
                  <div className="absolute bottom-0 left-0 bg-blue-500/5 h-full z-0 transition-all" style={{width: `${Math.min(100, t.current_volume * 10)}%`}}></div>
                </div>
             ))}
           </div>
        </div>

        {/* Bottom: Hotspot Forecast */}
        <div className="flex-1 glass-panel flex flex-col overflow-hidden">
           <div className="p-5 border-b border-border bg-surface/50">
             <h2 className="font-semibold flex items-center gap-2"><MapPin size={18} className="text-blue-500"/> Forecast Hotspots</h2>
           </div>
           <div className="flex-1 overflow-y-auto p-5 grid grid-cols-1 gap-4">
             {data.hotspots.map((h, i) => (
                <div key={i} className="bg-surface border border-border p-4 rounded-lg flex items-center gap-6">
                  <div className="w-48">
                    <h3 className="font-bold text-lg text-white">{h.entity_id} District</h3>
                    <span className={`mt-1 inline-block px-2 py-1 rounded text-[10px] font-bold uppercase tracking-widest border ${getCategoryClass(h.category)}`}>
                      {h.category}
                    </span>
                  </div>
                  
                  <div className="flex items-center gap-4 px-6 border-x border-border/50">
                    <div className="text-center">
                      <div className="text-2xl font-bold text-muted">{h.current_score.toFixed(0)}</div>
                      <div className="text-[10px] uppercase text-muted font-semibold tracking-wider">Current</div>
                    </div>
                    <Activity className="text-blue-500 opacity-50" />
                    <div className="text-center">
                      <div className="text-3xl font-black text-white">{h.projected_score.toFixed(0)}</div>
                      <div className="text-[10px] uppercase text-blue-400 font-semibold tracking-wider">Projected</div>
                    </div>
                  </div>
                  
                  <div className="flex-1 pl-2">
                    <p className="text-sm font-semibold text-white mb-1">{h.prediction}</p>
                    <p className="text-xs text-muted flex items-start gap-1"><ChevronRight size={14} className="shrink-0 mt-0.5 text-blue-500"/> {h.reason}</p>
                  </div>
                  
                  <div className="w-16 text-right">
                    <div className="text-xs font-bold text-green-400">{(h.confidence * 100).toFixed(0)}%</div>
                    <div className="text-[9px] uppercase text-muted font-bold tracking-wider">Conf.</div>
                  </div>
                </div>
             ))}
           </div>
        </div>

      </div>
    </div>
  );
};

export default Forecast;
